<?php
    //start the session
    session_start();
    //check for id
   if(isset($_GET['id'])){
    // $url_id = $_GET['id'];
    //Ensure that the id is accurate
    if(($_GET['id'] == $_SESSION['id']) || !empty($url_id) || ($url_id !== NULL) || (!empty($id) || ($id !== NULL))){
      //We passed
    }else{
        //Redirect back to the login page if id doesnt match the one generated by the system
      header("Location: ../");
    }
   }else{
       //Redirect if not logged in
       header("Location: ../");
   }

?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/bootstrap.css">
    <title>Make A Suggestion</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">School Name</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
    </ul>
  </div>
</nav>
<br> <br>
<div class="container">

<form action="index.php" method="post">
    <div class="form-group">
        <label>Write your comment ,</label>
        <textarea name="suggestion" id="" cols="30" rows="10" class="form-control" required></textarea>
    </div>
    <div class="form-group">
        <input type="submit" name="publish" value="Publish" class="form-control btn btn-primary">
    </div>
</form>
</div>
</body>
</html>